"""empty message

Revision ID: 1173cdfc8010
Revises: None
Create Date: 2016-06-17 05:26:14.106396

"""

# revision identifiers, used by Alembic.
revision = '1173cdfc8010'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('bldtype', sa.String(), nullable=True))
    op.add_column('test', sa.Column('datetimefrom', sa.DateTime(), nullable=True))
    op.add_column('test', sa.Column('datetimeto', sa.DateTime(), nullable=True))
    op.add_column('test', sa.Column('eventid', sa.NUMERIC(), nullable=False))
    op.add_column('test', sa.Column('locx', sa.NUMERIC(), nullable=True))
    op.add_column('test', sa.Column('locy', sa.NUMERIC(), nullable=True))
    op.add_column('test', sa.Column('prcode', sa.NUMERIC(), nullable=True))
    op.drop_column('test', 'pr_code')
    op.drop_column('test', 'datetime_from')
    op.drop_column('test', 'event_id')
    op.drop_column('test', 'bld_type')
    op.drop_column('test', 'loc_x')
    op.drop_column('test', 'loc_y')
    op.drop_column('test', 'datetime_to')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('datetime_to', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('test', sa.Column('loc_y', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('test', sa.Column('loc_x', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('test', sa.Column('bld_type', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('test', sa.Column('event_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('test', sa.Column('datetime_from', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('test', sa.Column('pr_code', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('test', 'prcode')
    op.drop_column('test', 'locy')
    op.drop_column('test', 'locx')
    op.drop_column('test', 'eventid')
    op.drop_column('test', 'datetimeto')
    op.drop_column('test', 'datetimefrom')
    op.drop_column('test', 'bldtype')
    ### end Alembic commands ###
